### ISSUE TITLE
Add test for coroutine

### ISSUE THREAD

**Issue by Keda87** [Keda87/PyGramedia#1]
I have difficulties to test coroutine based function.

**Comment by SukiCZ** [comment]
Hi,
I made an easy test for fetching product detail :smile: See PR #2 
Let me know if you want to have total coverage :godmode: current status:
```
Name                   Stmts   Miss  Cover   Missing
----------------------------------------------------
pygramed/__init__.py      53     10    81%   59-62, 84, 95-98, 108
tests.py                  20      0   100%
----------------------------------------------------
TOTAL                     73     10    86%
```

Cheers :clap:

**Comment by Keda87** [comment]
Hi @SukiCZ , thank you!
I think integrate coverage to this project also a good idea 😅
